apiVersion: v1
kind: ConfigMap
metadata:
  name: services-config
  namespace: outdoors-app
data:
  SPRING_PROFILES_ACTIVE: k8s
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservices_db
  SPRING_DATASOURCE_USERNAME: user