apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
  namespace: outdoors-app
spec:
  type: ClusterIP
  ports:
  - port: 9093
    targetPort: 9093
  selector:
    app: marketplace-service